### ISSUE TITLE
Unable to find C & CXX compiler on Mac OS

### ISSUE THREAD

**Issue by chancsc** [Erotemic/vtool_ibeis#1]
## When running setup on Mac, encountered error on compiler not found, updated the CMakeLists.txt as following:

if (APPLE AND CLANG2)
    message("Using clang2")

```
#Commented off the following 2 lines
#set(CMAKE_C_COMPILER "clang2")
#set(CMAKE_CXX_COMPILER "clang2++”)

#replaced with full path
set(CMAKE_C_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc")
set(CMAKE_CXX_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++")
```

endif()

---

**Comment by bluemellophone** [comment]
The problem is that the stock clang compiler on OS X does not support OpenMP compiler directives and thus cannot optimize supported code for multi-threading.

As a result, our installation requires a new version of clang with -lgomp support to be built by the user and used when compiling code on OS X.  Of course, this option can be safely turned off by setting the CLANG2 Cmake variable to 'Off', but comes at the price of slower, single-threaded run times.

To install clang2, follow the instructions here: http://stackoverflow.com/a/21789869
